# This is a basic workflow to help you get started with Actions
name: Build

# Controls when the workflow will run
on:
  # Shedule 1 fois par semaine
  schedule:
    - cron: "0 16 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  github-pipeline-library:
    uses: laveracloudsolutions/github-pipeline-library/.github/workflows/build.yml@main
    with:
      config-path: .github/images.json
    secrets: inherit